### ISSUE TITLE
the scraper skip some tweets when using --until

### ISSUE THREAD

**Issue by minamotorin** [minamotorin/twint#12]
I found that this part of the code in `url.py`

```
    if "win" in platform:
        return f'\"{date.split()[0]}\"'
```

sometimes makes the scraper skip some tweets when using --until "%y-%m-%d %H:%M:%S" on Windows. It starts from some hours before the specified one. Removing these lines seems to achieve better results.

_Originally posted by @Tortar in https://github.com/minamotorin/twint/issues/8#issuecomment-1186351007_

**Comment by minamotorin** [comment]
@Tortar
The code you pointed out was originally added as a workaround for https://github.com/twintproject/twint/issues/597.
When I fixed https://github.com/twintproject/twint/issues/1136, I changed the one (https://github.com/minamotorin/twint/commit/188e521ec4aa37e1cc4bd4c6f22e50234b4a9f39).
But I doesn't remove the code because I can't deny the possibility that https://github.com/twintproject/twint/issues/597 has recur.

If someone helps debugging on Windows and https://github.com/twintproject/twint/issues/597 resolves, I would be able to remove the code.

**Comment by Tortar** [comment]
okay no problem...Just to add something to the discussion I can say that more you go back in time more the number of results before the scraper stops becomes lower, in the order of a day of results

**Comment by Tortar** [comment]
Actually...on Windows works perfectly without
```

    if "win" in platform:
        return f'\"{date.split()[0]}\"'
```

, I tried:

`
twint -s pineapple --until "2020-11-09 9:00:00" --since "2020-11-09 1:00:00"`

and 

`twint -s pineapple --until "2020-11-09" --since "2020-11-08"`

and they work as expected, stopping at the right point
