### ISSUE TITLE
Possible unused dependency blocking upgrade to python 3.11

### ISSUE THREAD

**Issue by M-C-Sec** [minamotorin/twint#14]
# Description of Issue
 I've just been trying to get this twint fork running on python 3.11, but was coming up against issues installing the requirements, as cchardet doesn't have compatibility for 3.11 (see [this issue](https://github.com/PyYoshi/cChardet/issues/81)). There's a fork linked in that thread which is compatible with 3.11, but when I went looking through the twint code for any instances of cchardet I couldn't find anything - it doesn't seem to be imported or referenced anywhere other than the requirements.
Unless I'm missing something, it might be worth removing it as a requirement for the sake of onward compatibility (and the nice performance boost from 3.11!).

I've done some basic tests on my own build and had no issues with removing it, although as it's an encoding library and these were only English language tweets it's perhaps worth some testing with other languages too.

# Environment Details
Running in a venv with python 3.11, on macOS Monterey 12.6.1

**Comment by minamotorin** [comment]
@M-C-Sec Thanks for your report.

I agree with your opinion and I'll remove cChardet from requirements.
cChardet was added at db08c90502a99361877b85c51739f7906cc0c971 but it seems cChardet has never been imported as you say.
