### ISSUE TITLE
It just doesn't scrap all the tweets and stop scrapping randomly

### ISSUE THREAD

**Issue by Ramizworking** [minamotorin/twint#15]
Hey guys

I am just running twint -s "word" --since 2022-12-29" and it just stops even before reaching to 29th. It stops after 100 tweets at 13:45:00 2022-12-30 when it should continue scrapping..

Would you mind fixing this ? For some words it works  perfectly but some words like "liquidity" , it stops randomly

Thanks

**Comment by minamotorin** [comment]
Duplicate of #8.
